spring:
  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@14.36.141.71:10052:xe

    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@14.36.141.71:10052:xe
    
    username: COMA
    password: COMA
    hikari : 
      maximum-pool-size: 10
      minimum-idle: 5

  mvc:
    view: 
      prefix: /WEB-INF/views/
      suffix: .jsp 
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp

mybatis: 
  mapper-locations: classpath:mappers/**/*.xml 
  config-location: classpath:config/mybatis-config.xml

#logging: 
# file: 
#  name: log/springboot.log
# level:
#  '[com.coma]' : debug 
#  '[javax.sql]': info
#  '[jdbc.resultset]': OFF
#  '[jdbc.sqlonly]': info
#  '[jdbc.connection]': OFF

logging:
  level:
    '[com.coma]': debug
    jdbc.sqlonly: off
    jdbc.resultsettable: off
    jdbc.audit: OFF
    jdbc.resultset: off
    jdbc.connection: error
    jdbc.sqltiming: debug
    org.springframework.web: info



   